#!/bin/bash

set -u

readonly scriptdir="$(dirname ${BASH_SOURCE[0]})"
readonly configdir="$HOME/.config"
readonly dotfiledir="$configdir/dotfiles"

for file in $*; do
    diff -u "$dotfiledir/$file" "$scriptdir/$file"
done
