#!/bin/bash
# install config files

set -eu
source utils

script_name="$(basename $BASH_SOURCE)"
is_interactive=0
[ "$#" -gt 0 ] && [[ "$@" =~ "-i" ]] && is_interactive=1

create_dirs() {
    msg "Creating directories..."

    local directories="$(find $scriptdir/files -type d | tail -n+2 | sed 's|^'$scriptdir/files'/||')"
    local directory

    for directory in $directories; do
        mkdir -vp "$HOME/$directory"
    done

    msg_done

}

copy_files() {
    create_dirs

    msg "Copying files..."

    local files="$(find $scriptdir/files -type f | sed 's|^'$scriptdir/files'/||')"
    local file

    for file in $files; do
        cp -v "$filedir/$file" "$HOME/$file"
    done

    msg_done
}

exec_step() {
    if [ "$is_interactive" = "1" ]; then
        read -p "> $*? [Y/n/q] " choice
        case "$choice" in
            y|Y|"") $*;;
            q) printf "\n<<< Skipping rest of $script_name...\n\n"; exit 0;;
            n|N|*) ;;
        esac
    else
        $*
    fi
}

main() {
    msg "Starting $script_name...\n"

    exec_step copy_files

    printf "\n<<< Completed $script_name.\n\n"
}

main
