#!/bin/bash
# dotfiles installer

set -eu

readonly kernel="$(uname -s)"
readonly scriptdir="$(dirname ${BASH_SOURCE[0]})"
readonly configdir="${XDG_CONFIG_HOME:-$HOME/.config}"
readonly dotfiledir="$configdir/dotfiles"
readonly backupdir="$dotfiledir/backup"
readonly bindir="$HOME/code/bin"

die() {
    printf "ERROR: $*\n"
    exit 1
}

edone() {
    printf "done\n\n"
}

has() {
    type -p $* &>/dev/null
}

exists() {
    local file
    for file in $*; do
        test -e "$file" || return 1
    done
}

is_linux() {
    test "$kernel" = Linux
}

is_mac() {
    test "$kernel" = Darwin
}

dl() {
    if has curl; then
        curl -#fLo $*
    elif has wget; then
        wget --show-progress -qO $*
    else
        die "no curl or wget found"
    fi
}

backup_config() {
    printf "Backing up existing config files to $backupdir...\n"
    mkdir -p "$backupdir"

    local file
    for file in $files; do
        exists "$HOME/.$file" && cp -v "$HOME/.$file" "$backupdir/$file"
    done

    exists "$configdir/nvim/init.vim" && cp -v "$_" "$backupdir/init.vim"
    exists "$configdir/git/config" && cp -v "$_" "$backupdir/git_config"
    exists "$configdir/git/ignore" && cp -v "$_" "$backupdir/git_ignore"
    exists "$configdir/i3/config" && cp -v "$_" "$backupdir/i3_config"
    exists "$configdir/i3status/config" && cp -v "$_" "$backupdir/i3status_config"
    exists "$configdir/i3blocks/config" && cp -v "$_" "$backupdir/i3blocks_config"
    exists "$configdir/kitty/kitty.conf" && cp -v "$_" "$backupdir/kitty.conf"
    exists "$configdir/alacritty/alacritty.yml" && cp -v "$_" "$backupdir/alacritty.yml"

    edone
}

copy_config() {
    printf "Copying config files to $dotfiledir...\n"
    mkdir -p "$dotfiledir"

    local file
    for file in $files; do
        cp -v "$scriptdir/$file" "$dotfiledir"
    done

    local dirfiles="git_config git_ignore "
    dirfiles+="kitty.conf alacritty.yml "
    is_linux && dirfiles+="i3_config i3status_config i3blocks_config"
    for file in $dirfiles; do
        cp -v "$scriptdir/$file" "$dotfiledir"
    done

    edone
}

link_config() {
    printf "Linking config files...\n"

    local file
    for file in $files; do
        ln -vsf "$dotfiledir/$file" "$HOME/.$file"
    done

    test -h "$configdir/nvim" && rm "$configdir/nvim"
    mkdir -p "$configdir/nvim"
    cat > "$configdir/nvim/init.vim" <<EOF
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
EOF

    mkdir -p "$configdir/git"
    ln -vsf "$dotfiledir/git_config" "$configdir/git/config"
    ln -vsf "$dotfiledir/git_ignore" "$configdir/git/ignore"

    if is_linux; then
        mkdir -p "$configdir/"{i3,i3status,i3blocks}
        ln -vsf "$dotfiledir/i3_config" "$configdir/i3/config"
        ln -vsf "$dotfiledir/i3status_config" "$configdir/i3status/config"
        ln -vsf "$dotfiledir/i3blocks_config" "$configdir/i3blocks/config"
    fi

    mkdir -p "$configdir/kitty"
    ln -vsf "$dotfiledir/kitty.conf" "$configdir/kitty/kitty.conf"
    mkdir -p "$configdir/alacritty"
    ln -vsf "$dotfiledir/alacritty.yml" "$configdir/alacritty/alacritty.yml"

    edone
}

configure_mac() {
    is_mac || return 1

    # Expand save panels
    defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
    defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

    # Disable automatic text meddling
    defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
    defaults write -g NSAutomaticCapitalizationEnabled -bool false
    defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
    defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
    defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false

    # Show filename extensions
    defaults write -g AppleShowAllExtensions -bool true

    # Disable inverted scrolling
    defaults write -g com.apple.swipescrolldirection -bool false

    # Enable font smoothing
    defaults write -g CGFontRenderingFontSmoothingDisabled -bool false

    # Disable animations
    defaults write -g NSAutomaticWindowAnimationsEnabled -bool false
    defaults write -g QLPanelAnimationDuration -float 0
    defaults write com.apple.finder DisableAllAnimations -bool true

    # Show full paths
    defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

    # Autohide Dock
    defaults write com.apple.dock autohide -bool true

    # Disable screenshot shadows
    defaults write com.apple.screencapture disable-shadow -bool true

    # Show ~/Library in Finder
    chflags nohidden ~/Library

    killall Dock Finder
}

install_homebrew() {
    is_mac || return 1

    if has brew; then
        printf "Homebrew already installed, skipping...\n"
        return
    fi

    printf "Installing Homebrew...\n"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    edone
}

install_vimplug() {
    printf "Installing vim-plug...\n"

    local plugdir="$HOME/.vim/autoload"
    local url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

    mkdir -p "$plugdir"
    dl "$plugdir/plug.vim" "$url"

    if has vim; then
        vim +PlugUpdate +qa
        edone
    elif has nvim; then
        nvim +PlugUpdate +qa
        edone
    else
        printf "No vim or neovim found, skipping vim-plug install.\n"
        return
    fi
}

install_fzf() {
    printf "Installing fzf...\n"

    local fzfdir="$HOME/.fzf"
    local url="https://github.com/junegunn/fzf.git"

    if test -x "$fzfdir/install"; then
        (
        cd "$fzfdir"
        if ! git diff --quiet origin/master; then
            git stash
            git pull
        fi
        )

        "$fzfdir/install" --key-bindings \
                          --completion \
                          --no-update-rc \
                          --no-zsh \
                          --no-fish \
                          1>/dev/null
        edone
    elif has git; then
        rm -rf "$fzfdir"
        git clone --depth 1 "$url" "$fzfdir"
        chmod g+x "$fzfdir/install"

        "$fzfdir/install" --key-bindings --completion --no-update-rc 1>/dev/null
        edone
    else
        printf "Git not found, skipping fzf install.\n"
        return
    fi
}

install_z() {
    printf "Installing z...\n"

    local zdir="$configdir/z"
    local url="https://raw.githubusercontent.com/rupa/z/master/z.sh"

    mkdir -p "$zdir"
    dl "$zdir/z.sh" "$url"

    edone
}

install_v() {
    printf "Installing v...\n"

    local url="https://raw.githubusercontent.com/rupa/v/master/v"

    mkdir -p "$bindir"

    dl "$bindir/v" "$url"
    chmod ug+x "$bindir/v"

    edone
}

main() {
    local files="bash_profile bashrc vimrc tmux.conf"

    if is_mac; then
        files+=" xvimrc"
        configure_mac
        install_homebrew
    elif is_linux; then
        files+=" xinitrc Xmodmap Xresources"
    fi

    backup_config
    copy_config
    link_config

    install_fzf
    install_vimplug
    install_z
    install_v

    printf "all done\n"
}

main
